name: Build & Test Validaide/GoogleMapBundle
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        operating-system: [ ubuntu-latest ]
        php-versions: [ '7.4','8.1' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2,phpstan
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install PHP Dependencies (composer)
        run: composer install --optimize-autoloader --no-suggest --no-scripts
        env:
          COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{secrets.COMPOSER_GITHUB_ACTIONS }}"} }'
          SYMFONY_ENV: test

      - name: PHPUnit
        run: vendor/bin/phpunit

